//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELinkLogViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string cover { get; set; }
        public string branch { get; set; }
        public string client { get; set; }
        public string clientnumber { get; set; }
        public string invoice { get; set; }
        public string clienttransaction { get; set; }
        public string policytransaction { get; set; }
        public string version { get; set; }
        public string filecontents { get; set; }
        public string filename { get; set; }
        public System.DateTime timestamp { get; set; }
        public string type { get; set; }
        public string status { get; set; }
    }
}
